import { AITool } from './types';

export const aiTools: AITool[] = [
  {
    id: "1",
    name: "Nuance DAX",
    vendor: "Microsoft (Nuance Communications)",
    users: ["Providence", "Stanford Health Care", "University of Michigan Health", "WellSpan Health", "Rush University"],
    type: ["Hospitals", "Enterprises", "Solo Practitioners"],
    category: "Operations",
    workflow: "Documentation & Scribing",
    problemSolved: "Reduces physician burnout by automating clinical note-taking during patient encounters, saving an average of 7 minutes per encounter.",
    successRate: "Used by hundreds of hospitals globally; reduces time spent on documentation by 50% and improves physician satisfaction by 70%. Active since 2020.",
    status: "Active",
    year: "2020 - Present",
    useCases: ["Ambient clinical intelligence during visits", "Automated SOAP note generation", "EHR integration"],
    issues: "High cost of implementation, requires an adjustment period for clinicians to trust the AI's transcription accuracy, occasional errors in complex medical terminology.",
    legalCases: "None significant; standard data privacy (HIPAA) compliance scrutiny.",
    aiSupportLevel: "Partial AI Support",
    aiSupportLevelExplanation: "Drafts notes from ambient audio, but requires physician review, editing, and signature."
  },
  {
    id: "2",
    name: "Olive",
    vendor: "Olive AI",
    users: ["Tufts Medicine (Past)", "OhioHealth (Past)", "Essentia Health (Past)", "Gundersen Health (Past)"],
    type: ["Hospitals", "Enterprises"],
    category: "Revenue Cycle Management",
    workflow: "Prior Authorization & Eligibility",
    problemSolved: "Aimed to automate repetitive administrative tasks like prior authorizations, eligibility checks, and claim status inquiries.",
    successRate: "Initially deployed in over 900 hospitals at its peak, claiming up to 30% reduction in administrative overhead.",
    status: "Inactive",
    year: "2012 - 2023",
    useCases: ["Automated prior authorization submissions", "Patient eligibility verification", "Supply chain management"],
    issues: "Failed to deliver on ROI promises for many customers, issues with software reliability and scalability, over-promised AI capabilities that ended up requiring heavy human-in-the-loop dependencies.",
    legalCases: "Sued by multiple vendors for unpaid bills during its financial collapse in late 2023. Ultimately shut down and sold off assets.",
    aiSupportLevel: "Full AI Replacement",
    aiSupportLevelExplanation: "Designed to fully automate administrative tasks like prior authorizations with minimal human intervention, though it struggled in practice."
  },
  {
    id: "3",
    name: "Viz.ai",
    vendor: "Viz.ai",
    users: ["Mount Sinai Health System", "Cleveland Clinic", "HCA Healthcare", "Geisinger", "Valley Health"],
    type: ["Hospitals", "Specialty Clinics"],
    category: "Diagnostics",
    workflow: "Diagnostics & Triage",
    problemSolved: "Delays in diagnosing and treating large vessel occlusion (LVO) strokes by analyzing CT scans and automatically alerting stroke teams.",
    successRate: "Implemented in 1,200+ hospitals. Reduces time to treatment by over 22 minutes on average. De Novo FDA clearance obtained in 2018.",
    status: "Active",
    year: "2016 - Present",
    useCases: ["Stroke detection", "Pulmonary embolism triage", "Aortic disease detection", "Care team coordination via mobile app"],
    issues: "False positives can lead to alarm fatigue. High reliance on the quality of the initial CT scan.",
    legalCases: "Standard regulatory oversight. Holds FDA clearance, ensuring rigorous clinical trial evidence. No major controversies.",
    aiSupportLevel: "Partial AI Support",
    aiSupportLevelExplanation: "AI flags potential stroke cases and notifies doctors, but a specialist must review the scan to make the final clinical diagnosis."
  },
  {
    id: "4",
    name: "Waystar",
    vendor: "Waystar",
    users: ["Intermountain Healthcare", "Bon Secours Mercy Health", "AdventHealth", "Baptist Health"],
    type: ["Hospitals", "Enterprises", "Solo Practitioners"],
    category: "Revenue Cycle Management",
    workflow: "Billing & Credentialing",
    problemSolved: "Inefficiencies and errors in medical billing, claims denial management, and slow provider credentialing processes.",
    successRate: "Used by over 500,000 providers and 1,000 hospitals. Claims a 98% first-pass clean claim rate.",
    status: "Active",
    year: "2017 - Present",
    useCases: ["Denial prevention and recovery", "Automated provider credentialing", "Patient financial clearance"],
    issues: "Complex integration processes with legacy EHR systems. Steep learning curve for new billing staff.",
    legalCases: "None documented outside of routine corporate compliance.",
    aiSupportLevel: "Partial AI Support",
    aiSupportLevelExplanation: "Automates the transmission and scoring of claims, but requires human billing staff to handle complex denials and exceptions."
  },
  {
    id: "5",
    name: "Suki Assistant",
    vendor: "Suki AI",
    users: ["Ascension", "Franciscan Health", "Texas Health Resources", "Centerstone"],
    type: ["Solo Practitioners", "Small to Mid-sized Clinics"],
    category: "Operations",
    workflow: "Documentation & Scribing",
    problemSolved: "EHR data entry burden causing late-night charting for smaller practice doctors.",
    successRate: "Reduces documentation time by 72% on average. Used by thousands of providers across various specialties.",
    status: "Active",
    year: "2017 - Present",
    useCases: ["Voice-dictated clinical notes", "ICD-10 coding assistance", "EHR data retrieval via voice command"],
    issues: "Voice recognition struggles with heavy accents or very noisy clinic environments.",
    legalCases: "Compliant with HIPAA. No major controversies.",
    aiSupportLevel: "Partial AI Support",
    aiSupportLevelExplanation: "Assists with note creation and coding, but the physician must review the final output and sign the chart."
  },
  {
    id: "6",
    name: "Corti",
    vendor: "Corti",
    users: ["Priority Dispatch", "Copenhagen EMS", "Seattle Fire Department"],
    type: ["Hospitals", "Public Safety Answering Points (PSAPs)"],
    category: "Diagnostics",
    workflow: "Triage & Consultations",
    problemSolved: "Identifies critical illnesses like cardiac arrest during emergency calls by analyzing voice and background noises to assist dispatchers.",
    successRate: "Used globally in emergency dispatch centers; shown to predict cardiac arrests earlier and with higher accuracy (92%) than human dispatchers alone.",
    status: "Active",
    year: "2016 - Present",
    useCases: ["Cardiac arrest detection over phone", "Post-call documentation", "Quality assurance and training"],
    issues: "Requires high-quality audio feeds, can be affected by ambient chaos or poor connection.",
    legalCases: "Requires strict adherence to international data privacy laws (GDPR/HIPAA) regarding audio recordings, but no major lawsuits.",
    aiSupportLevel: "Partial AI Support",
    aiSupportLevelExplanation: "Listens to 911 calls and suggests diagnoses, but the human dispatcher retains full control over triage and response decisions."
  },
  {
    id: "7",
    name: "Abridge",
    vendor: "Abridge",
    users: ["UPMC", "Emory Healthcare", "Sutter Health", "Yale New Haven Health", "UCI Health", "Kaiser Permanente (Pilot)"],
    type: ["Hospitals", "Health Systems"],
    category: "Operations",
    workflow: "Documentation & Scribing",
    problemSolved: "Reduces the cognitive load of documentation by generating draft clinical notes directly from patient conversations, alleviating physician burnout.",
    successRate: "Saves clinicians 2+ hours per day on average; 91% of notes require minimal to no edits. Adopted rapidly by dozens of top US health systems.",
    status: "Active",
    year: "2018 - Present",
    useCases: ["Ambient listening", "Structured medical note generation", "Deep EHR integration (Epic)"],
    issues: "Requires comprehensive clinical review by the physician to ensure no critical omissions. Occasional misinterpretation of overlapping dialogue in noisy rooms.",
    legalCases: "Complies with HIPAA; no major lawsuits documented.",
    aiSupportLevel: "Partial AI Support",
    aiSupportLevelExplanation: "Automatically generates draft clinical notes from visit audio, but relies on the physician to edit and finalize the note."
  },
  {
    id: "8",
    name: "Aidoc",
    vendor: "Aidoc",
    users: ["Cedars-Sinai", "Novant Health", "Corewell Health", "Ochsner Health", "Yale New Haven Health"],
    type: ["Hospitals", "Specialty Clinics", "Radiology Groups"],
    category: "Diagnostics",
    workflow: "Diagnostics & Triage",
    problemSolved: "Backlogs in radiology reading rooms, leading to missed or delayed detection of acute abnormalities like intracranial hemorrhage or pulmonary embolism.",
    successRate: "Analyzes millions of scans annually across 1,000+ facilities. Reduces turnaround time for critical cases by up to 39%. Holds 13 FDA clearances.",
    status: "Active",
    year: "2016 - Present",
    useCases: ["Intracranial hemorrhage detection", "Pulmonary embolism detection", "Incidental findings triage", "Care coordination for imaging"],
    issues: "Algorithm drift requires continuous monitoring. Integration can initially disrupt established radiologist workflows until they adapt to 'always-on' alerts.",
    legalCases: "Operates under FDA regulation; no major litigation. Ensures rigid data de-identification agreements.",
    aiSupportLevel: "Partial AI Support",
    aiSupportLevelExplanation: "Analyzes radiology scans in the background to prioritize worklists, but does not autonomously produce a final diagnostic report."
  },
  {
    id: "9",
    name: "Notable",
    vendor: "Notable Health",
    users: ["Intermountain Health", "Medical University of South Carolina (MUSC)", "Reid Health", "Marshfield Clinic"],
    type: ["Hospitals", "Enterprises"],
    category: "Operations",
    workflow: "Patient Intake & Scheduling",
    problemSolved: "High administrative burden on front-desk staff, long patient wait times during registration, and high no-show rates among populations.",
    successRate: "Automates up to 90% of front-desk administrative tasks for participating patients. Reduces registration times by up to 50% and improves patient satisfaction scores.",
    status: "Active",
    year: "2017 - Present",
    useCases: ["Digital mobile registration", "Pre-visit clinical intake", "Intelligent scheduling", "Prior authorization triage"],
    issues: "Success is heavily reliant on patients adopting mobile-first interfaces. Deep, custom integration with legacy EHR environments is resource-intensive.",
    legalCases: "No major litigation. Adheres to standard enterprise BAA and HIPAA frameworks.",
    aiSupportLevel: "Partial AI Support",
    aiSupportLevelExplanation: "Automates patient communication and data entry, but clinic staff still review schedules and handle patient exceptions manually."
  },
  {
    id: "10",
    name: "Nabla",
    vendor: "Nabla",
    users: ["The Permanente Medical Group (Kaiser Permanente)", "Children's Hospital Los Angeles", "Mankato Clinic"],
    type: ["Hospitals", "Enterprises", "Solo Practitioners"],
    category: "Operations",
    workflow: "Documentation & Scribing",
    problemSolved: "Time-consuming clinical documentation. Offered a privacy-first ambient alternative that deliberately does not store audio after the encounter.",
    successRate: "Rolled out to over 10,000 Kaiser Permanente physicians. Rapid adoption fueled by high accuracy and local processing compliance. Saves 1.5 - 2 hours daily.",
    status: "Active",
    year: "2020 - Present",
    useCases: ["Ambient clinical scribing", "Automated clinical coding generation", "Patient instruction generation"],
    issues: "Because no audio is stored (by design), clinicians cannot easily re-listen to encounters if the transcript misses nuances, forcing reliance on the initial AI capture.",
    legalCases: "None. Heavily markets its strict privacy policies (does not train on customer data without consent), effectively lowering liability.",
    aiSupportLevel: "Partial AI Support",
    aiSupportLevelExplanation: "Drafts medical notes in real-time without storing audio. Physicians must review the text and take responsibility for its medical accuracy."
  },
  {
    id: "11",
    name: "Fathom",
    vendor: "Fathom",
    users: ["ApolloMD", "Vituity", "Corewell Health"],
    type: ["Hospitals", "Emergency Departments", "Revenue Cycle Companies"],
    category: "Revenue Cycle Management",
    workflow: "Medical Coding",
    problemSolved: "Severe shortage of certified medical coders and high error rates in manual coding, leading to denied claims, compliance risks, and delayed revenue.",
    successRate: "Automates up to 90% of a health system's coding volume with reported 95%+ accuracy. Exceptionally strong in high-volume areas like emergency medicine.",
    status: "Active",
    year: "2015 - Present",
    useCases: ["Autonomous medical coding", "Denial reduction and predictive modeling", "Concurrent coding audits"],
    issues: "Requires massive sets of historical data specific to a health system's localized billing behaviors to achieve peak accuracy. Less effective in obscure super-specialties.",
    legalCases: "Routine compliance with CMS coding guidelines. No major litigation.",
    aiSupportLevel: "Partial AI Support",
    aiSupportLevelExplanation: "Autonomously processes a large portion of medical coding, but falls back to human expert coders for complex or low-confidence charts."
  },
  {
    id: "12",
    name: "Hippocratic AI",
    vendor: "Hippocratic AI",
    users: ["OhioHealth", "Memorial Hermann", "Healthfirst", "Cincinnati Children's"],
    type: ["Hospitals", "Health Systems"],
    category: "Operations",
    workflow: "Patient Engagement & Triage",
    problemSolved: "Nurse shortages leading to poor post-acute care follow-up and chronic care management, which increases hospital readmission risks.",
    successRate: "Early adoption phase. The LLM has been built specifically for healthcare and tested extensively against safety benchmarks, outperforming general LLMs in medical safety.",
    status: "Active",
    year: "2023 - Present",
    useCases: ["Post-discharge follow-up calls via voice AI", "Pre-operative instructions", "Chronic care management outreach calling"],
    issues: "Still in early deployment stages across the US. High scrutiny on patient acceptance of taking clinical instruction from 'AI nurses' over the phone.",
    legalCases: "None. Formed specifically to counteract AI liability by heavily investing in safety/nursing benchmarks and utilizing human-in-the-loop oversight.",
    aiSupportLevel: "Partial AI Support",
    aiSupportLevelExplanation: "Conducts voice calls with patients for follow-ups, but relies on a rigid human-in-the-loop safety system to escalate issues to human nurses."
  }
];
